import { EyeOff, Lock, ShieldCheck } from "lucide-react";
import type { LegalDoc } from "./types";

export const PRIVACY: LegalDoc = {
  badge: { icon: ShieldCheck, label: "Your privacy is our priority" },
  title: "Privacy Policy",
  subtitle:
    "BlackQuant is committed to transparency about how we collect, use, and protect your personal data. Read our full privacy policy below.",
  updated: "Last updated: January 2025 · GDPR compliant",
  sections: [
    {
      title: "What Personal Data We Collect",
      cards: [
        {
          title: "Account Information",
          body: "When you create a BlackQuant account, we collect your email address, full name, phone number (optional), and preferred trading pairs. This allows us to personalize your experience and send account-related notifications.",
        },
        {
          title: "Trading Data",
          body: "We collect information about your trades, positions, withdrawals, and signals generated by our strategies. This data helps us improve strategy performance and provide you with accurate backtest results.",
        },
        {
          title: "Device & Usage Data",
          body: "We automatically collect information about how you access BlackQuant — your IP address, browser type, pages visited, and time spent on features. This helps us detect suspicious activity and optimize platform performance.",
        },
      ],
    },
    {
      title: "How We Use Your Data",
      cards: [
        {
          title: "To Provide Services",
          body: "Your data enables us to deliver trading signals, manage your account, process withdrawals, and provide customer support.",
        },
        {
          title: "To Improve & Develop",
          body: "We analyze trading patterns and signal effectiveness to refine our algorithms. We never use individual trade data for marketing without explicit consent.",
        },
        {
          title: "To Comply & Protect",
          body: "We use your data to prevent fraud, comply with regulatory requirements, and enforce our Terms of Service.",
        },
      ],
    },
    {
      title: "Data Security & Encryption",
      cards: [
        {
          title: "At Rest",
          body: "All data is encrypted using AES-256 encryption and stored in secure, ISO 27001-certified data centers.",
        },
        {
          title: "In Transit",
          body: "API calls and web traffic use TLS 1.3. All credentials are hashed using bcrypt (cost 12). We never store passwords in plaintext.",
        },
        {
          title: "Access Control",
          body: "Only authorized personnel can access user data. All data access is logged and audited.",
        },
      ],
    },
    {
      title: "Your Privacy Rights",
      cards: [
        {
          title: "Right to Access",
          body: "You can request a copy of all personal data we hold about you. Submit a request via Help Desk, and we'll respond within 14 days.",
        },
        {
          title: "Right to Deletion",
          body: "You can request deletion of your account and associated data. Deletion is permanent and will terminate all active strategies.",
        },
        {
          title: "Right to Rectification",
          body: "You can update or correct inaccurate information in your account settings at any time.",
        },
        {
          title: "Right to Portability",
          body: "You can request your data in a standard, machine-readable format (CSV/JSON).",
        },
      ],
    },
    {
      title: "Third-Party Data Sharing",
      cards: [
        {
          title: "No Sales",
          body: "We do NOT sell your personal data to third parties. Period.",
        },
        {
          title: "Required Disclosures",
          body: "We may disclose data only when legally required (court orders, regulatory investigations, law enforcement).",
        },
        {
          title: "Service Providers",
          body: "We use trusted vendors for payment processing, analytics, and email delivery. All vendors are bound by strict data processing agreements.",
        },
      ],
    },
    {
      title: "Cookies & Tracking",
      cards: [
        {
          title: "Essential Cookies",
          body: "Required for login, 2FA, and session management. Cannot be disabled.",
        },
        {
          title: "Functional Cookies",
          body: "Remember your preferences (theme, language, layout). You can disable via settings.",
        },
        {
          title: "Analytics Cookies",
          body: "Help us understand how you use BlackQuant. Fully anonymized and non-identifying. You can opt out.",
        },
      ],
    },
    {
      title: "Data Retention & Deletion",
      cards: [
        {
          title: "Active Accounts",
          body: "We retain your data for as long as your account is active.",
        },
        {
          title: "Deleted Accounts",
          body: "After deletion, data is permanently removed within 30 days, except where legal obligations require retention (e.g., AML/KYC records, kept 7 years).",
        },
        {
          title: "Backups",
          body: "Deleted data may persist in encrypted backups for up to 90 days for disaster recovery purposes.",
        },
      ],
    },
    {
      title: "International Data Transfers",
      cards: [
        {
          title: "GDPR Compliance",
          body: "If you're in the EU, your data is processed in accordance with GDPR. We use Standard Contractual Clauses for any transfers outside the EEA.",
        },
        {
          title: "Data Localization",
          body: "BlackQuant infrastructure is based in Singapore with redundancy in Asia-Pacific regions.",
        },
      ],
    },
    {
      title: "Contact & Disputes",
      cards: [
        {
          title: "Questions?",
          body: "Email privacy@blackquant.io with your request. We respond within 48 hours.",
        },
        {
          title: "Data Subject Rights",
          body: "If you believe we've mishandled your data, you have the right to file a complaint with your local data protection authority.",
        },
      ],
    },
  ],
  highlights: {
    heading: "Key Highlights",
    tone: "positive",
    cards: [
      {
        icon: ShieldCheck,
        title: "AES-256 Encryption",
        body: "All data encrypted at rest and in transit using industry-standard protocols.",
      },
      {
        icon: Lock,
        title: "GDPR Compliant",
        body: "Full compliance with EU data protection regulations and user rights.",
      },
      {
        icon: EyeOff,
        title: "No Data Sales",
        body: "We never sell your personal data to third parties, period.",
      },
    ],
  },
  faq: {
    heading: "Frequently Asked Questions",
    items: [
      {
        question: "How long do you keep my data?",
        answer: "We retain data while your account is active. After deletion, data is permanently removed within 30 days (except legally required records like AML/KYC, kept 7 years).",
      },
      {
        question: "Can I download my data?",
        answer: "Yes. Request your data via Help Desk, and we'll provide it in CSV/JSON format within 14 days. This includes all trades, transactions, and account information.",
      },
      {
        question: "Do you use my data for marketing?",
        answer: "No, not without explicit consent. We never use trading data for marketing purposes. You can opt out of all marketing emails in account settings.",
      },
      {
        question: "Who can access my trading data?",
        answer: "Only authorized BlackQuant staff can access your data, and only when necessary for support, fraud detection, or legal compliance. All access is logged.",
      },
      {
        question: "Is my data safe from breaches?",
        answer: "We use industry-standard security (AES-256, TLS 1.3, bcrypt). We maintain cybersecurity insurance and conduct regular security audits and penetration tests.",
      },
      {
        question: "What about cookies?",
        answer: "Essential cookies (login/2FA) are required. Functional and analytics cookies are optional. You can manage cookie preferences in account settings.",
      },
    ],
  },
  cta: {
    title: "Questions About Your Privacy?",
    body: "Our Data Protection Officer is here to help. Reach out via Help Desk or email privacy@blackquant.io.",
    emailLabel: "Email DPO",
    email: "privacy@blackquant.io",
  },
};
